### ISSUE TITLE
support CMake

### ISSUE THREAD

**Issue by irov** [crosire/blink#15]
Hello, maybe instead of sln, you should support CMake so that you can build for different studios?

I can create pull request

Thanks

**Comment by crosire** [comment]
Currently the code doesn't compile with anything older than VS2017, since it uses C++17, so not sure if that would be that useful?

**Comment by irov** [comment]
Coming soon VS2019. And maybe it will simplify the assembly of this project as a third-party library or tools.

**Comment by crosire** [comment]
Closing as this project is currently too specific to VS2017 for it to make sense to support other compilers via CMake.
