### ISSUE TITLE
cl.exe not found

### ISSUE THREAD

**Issue by Pombal** [crosire/blink#28]
Hi,

I've built a simple hello world application with /Zi and VS 17 community edition version 15.8.7 with an x64 build of the 19.00.24234.1 compiler.

I got an error saying it couldn't find cl.exe. Hard coding cl.exe to the correct path then gives the error: Cannot open include file 'windows.h'. I'd rather not have to mess around with vcvarsall.bat... 

Any ideas why this seems to work for other people but not on my machine? Thanks.

**Comment by crosire** [comment]
Compile your application with `/ZI`. Blink will not be able to deduce the build command-line if compiled with just `/Zi`.

**Comment by Pombal** [comment]
Cool, thanks. It does successfully link now but weirdly it doesn't do anything.

```
#include <Windows.h>
#include <iostream>

int main()
{
    while (true)
    {
        std::cout << "hello" << std::endl;
        Sleep(100);
    }
}
```

After changing "hello" to "hello world" it continues to print "hello" after linking, instead of the new string.

**Comment by crosire** [comment]
Please read the readme. Both things you asked so far are answered there.

See

**Comment by Pombal** [comment]
Got it now, thank you.

You are absolutely right but perhaps these points could be made more explicit? I did read the readme multiple times and still missed it ( /Zi is very similar to /ZI and the importance of having a function being called multiple times is easy to understate )

**Comment by crosire** [comment]
Fair enough. Made some changes to highlight these two things.
