### ISSUE TITLE
File watcher should watch subdirectories

### ISSUE THREAD

**Issue by optimizedaway** [crosire/blink#5]
File watcher only scans for changes in the root directory, subdirectories should also be watched.

**Comment by crosire** [comment]
It does actually watch subdirectories:
https://github.com/crosire/blink/blob/7a82c5017fcb8e2cb222261f85b7899983374980/source/file_watcher.cpp#L60 The `bWatchSubtree` parameter of `ReadDirectoryChangesW` is set to `TRUE`. It is working on my end.

**Comment by optimizedaway** [comment]
Yup, my fault, sorry
