### ISSUE TITLE
DWARF and other platforms?

### ISSUE THREAD

**Issue by ddovod** [crosire/blink#7]
Hi. Thank you very much for your work! Any chance to see the port of blink to use on another platforms? I'm not experienced in it, but I guess DWARF should have enough data for doing that. Are you aware of this?

**Comment by ddovod** [comment]
I see, anyway thank you very much!

**Comment by ddovod** [comment]
Hi again. Sorry for disturbing. Since you're not planning to support other platforms, could you consider placing the reference to [this] (https://github.com/ddovod/jet-live) library as an alternative for linux and macos?

**Comment by crosire** [comment]
Sure. Thanks for implementing the concept for Unix!

**Comment by ddovod** [comment]
As you might have guessed, your library inspired me to try this approach on non-windows, so thank you very much for inspiration!
